input {
  file {
    path => "/home/kali/aws-logs/*.json"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    type => "aws"
  }

  file {
    path => "/home/kali/azure-logs/*.json"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    type => "azure"
  }
}

filter {
  json {
    source => "message"
    target => "parsed_json"
    skip_on_invalid_json => true
  }

  mutate {
    add_field => {
      "cloud.provider" => "%{[parsed_json][source]}"
      "event_type"     => "%{[parsed_json][event_type]}"
      "user"           => "%{[parsed_json][user]}"
      "severity"       => "%{[parsed_json][severity]}"
      "message"        => "%{[parsed_json][message]}"
    }
    remove_field => ["host","path","@version","tags"]
  }

  date {
    match => ["[parsed_json][@timestamp]", "ISO8601"]
    target => "@timestamp"
    timezone => "UTC"
  }

  # Drop 404 or irrelevant logs if needed
  if [parsed_json][httpStatus] == "404" {
    drop { }
  }
}

output {
  elasticsearch {
    hosts => ["http://localhost:9200"]
    index => "multicloud-logs-final23-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}

